baseURL = "https://zhgyqc.netlify.app/"
languageCode = "en-us"
title = "Yu Ching San"
theme = "hugo-ht"
footnotereturnlinkcontents = "↩"
enableRobotsTXT = true
# enableGitInfo = true

[permalinks]
cn = "/cn/:year/:month/:day/:slug/"
en = "/en/:year/:month/:day/:slug/"
posts = "/posts/:year/:month/:day/:slug/"

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2
[[menu.en]]
    name = "Projects"
    url = "/en/projects/"
    weight = 3
[[menu.en]]
    name = "中文"
    url = "/cn/blogs/"
    weight = 4



[[menu.cn]]
    name = "博客"
    url = "/cn/blogs/"
    weight = 3
[[menu.cn]]
    name = "English"
    url = "/"
    weight = 4

[params]
    description = "Peronal website of Yu Ching San"
    homeText = "You just need a Hugo blog from scratch"
    # Please make sure `blogDirName` matches the name used in `menu` above:
    blogDirName = "blogs"
    # singleLang = true
    defaultLang = "en"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs" 
    MathJaxVersion = "2.7.5"
    favicon = "media/logo.png"
    # Edit by yourself:
    # GithubEdit = "https://github.com/USERNAME/REPONAME/edit/master/content/"
    copyright = "&copy;"
    copyrightYear = "2022-2023"
    # Edit by yourself:
    # GithubRepo = "https://github.com/Duguce/zhgyqc_site"
    # Edit by yourself:
    # ContentSource = "https://raw.githubusercontent.com/USERNAME/REPONAME/master/content/" 

[params.logo]
   # Change the logo picture as your prefer:
   url = "media/logo.png" # you can change it
   width = 50.0
   height = 50.0
   alt = "Hugo-ht"

[params.lang]

    [params.lang.author]
      en = "Yu Ching San"
      cn = "Yu Ching San"

    [params.lang.madeWith]
      en = "Made with"
      cn = "本站驱动"

    [params.lang.edit]
      en = "Suggest an edit of this page"
      cn = "编辑本页"

    [params.lang.lastupdate]
      en = "Last modified on"
      cn = "最后一次修改于"

    [params.lang.Sitelastupdate]
        en = "Site last updated on"
        cn = "最近一次更新于"

    [params.lang.sourceCode]
      en = "Content in"
      cn = "内容存于"

    [params.lang.subscribe]
      en = "Subscribe"
      cn = "订阅"

    [params.lang.license]
      en = "License"
      cn = "版权"

[markup]
 defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = false
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true

    [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false
  
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 4

  [markup.tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 2

[imaging]
quality = 100
